development:
  adapter: postgresql
  database: swot_development
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  database: swot_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  database: swot_test
  pool: 5
  username:
  password:
